### ISSUE TITLE
在第二步dbtoJson时，java进程遇到内存溢出错误

### ISSUE THREAD

**Issue by Coooolfan** [lqzhgood/Shmily-Get-Wechat#2]
在运行到第二步 dbtojson时报错内存溢出。为java程序的异常。
下为执行命令`node index`的控制台输出

```bash
正在解密 Message
java.lang.OutOfMemoryError: Java heap space
        at com.alibaba.fastjson.serializer.SerializeWriter.expandCapacity(SerializeWriter.java:308)
        at com.alibaba.fastjson.serializer.SerializeWriter.write(SerializeWriter.java:280)
        at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:430)
        at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:149)
        at com.alibaba.fastjson.serializer.ASMSerializer_1_Message.writeNormal(Unknown Source)
        at com.alibaba.fastjson.serializer.ASMSerializer_1_Message.write(Unknown Source)
        at com.alibaba.fastjson.serializer.ListSerializer.write(ListSerializer.java:79)
        at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:312)
        at com.alibaba.fastjson.JSON.toJSONString(JSON.java:687)
        at com.alibaba.fastjson.JSON.toJSONString(JSON.java:676)
        at sqlite.test.ReadTxt.main(ReadTxt.java:94)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
        at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
node:child_process:891
    throw err;
    ^

Error: Command failed: decodeMessageTable.exe
java.lang.OutOfMemoryError: Java heap space
        at com.alibaba.fastjson.serializer.SerializeWriter.expandCapacity(SerializeWriter.java:308)
        at com.alibaba.fastjson.serializer.SerializeWriter.write(SerializeWriter.java:280)
        at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:430)
        at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:149)
        at com.alibaba.fastjson.serializer.ASMSerializer_1_Message.writeNormal(Unknown Source)
        at com.alibaba.fastjson.serializer.ASMSerializer_1_Message.write(Unknown Source)
        at com.alibaba.fastjson.serializer.ListSerializer.write(ListSerializer.java:79)
        at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:312)
        at com.alibaba.fastjson.JSON.toJSONString(JSON.java:687)
        at com.alibaba.fastjson.JSON.toJSONString(JSON.java:676)
        at sqlite.test.ReadTxt.main(ReadTxt.java:94)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
        at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)

    at checkExecSyncError (node:child_process:817:11)
    at execSync (node:child_process:888:15)
    at Object.<anonymous> (C:\Users\Yang\Desktop\0601\Shmily-Get-Wechat\export\db-android\2 dbToJson\index.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  status: 1,
  signal: null,
    '\tat java.lang.reflect.Method.invoke(Unknown Source)\r\n' +
    '\tat com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)\r\n' +
    '\tat com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)\r\n'
}

Node.js v18.3.0
```

解密得到的`decrypted_database.db`文件大小1.05GB，猜测可能为文件大小过大 : (

此命令在Win11下运行，解密数据库的操作在Ubuntu中进行，解密过程并未报错。Windows的JAVA环境如下

```bash
java version "18" 2022-03-22
Java(TM) SE Runtime Environment (build 18+36-2087)
Java HotSpot(TM) 64-Bit Server VM (build 18+36-2087, mixed mode, sharing)
```

另，此java程序的所有代码是在`./test/`下吗。有意贡献代码（虽然水平不高🤪

**Comment by lqzhgood** [comment]
更新了一下，`decodeMessageTable.exe` java 最大内存修改至 4G
https://github.com/lqzhgood/Shmily-Get-Wechat/blob/0bfbe1d36ce1bde3f74ec71f5e935b4c94ff69af/export/db-android/2%20dbToJson/index.js#L13-L16

**Comment by lqzhgood** [comment]
`Java` 我是现学现卖的半吊子，目前已知还有以下问题。

- 代码优化
- 我不知道如何把 jre 打包进 exe，现在运行 `decodeMessageTable.exe` 还是需要 java 环境~
- 现在 `decodeMessageTable.exe` 没有入参，约等于硬编码 `decodeMessageTable.exe decrypted_database.db message.json`
   我设想可以修改为`decodeMessageTable.exe $i $o`  $i 为输入文件 $o 为输出文件
  - $i 
      - 默认值 `decrypted_database.db`
      - 支持相对路径和绝对路径
   - $o 
      -  默认值 `message.json`
      - 如果值为相对路径，输出路径相对 $i 计算。 （这样就不用复制 `decodeMessageTable.exe` 到 `input` 文件夹了）
      - 如果值为绝对路径，直接输出


如果有空可以帮忙改改吧，我电脑上没有 java runtime 了。

**Comment by Coooolfan** [comment]
感谢您这么晚了还在回复。我刚刚尝试了设置最大JVM内存为4G与7G扔显示相同的内存溢出。观察资源管理器在程序退出时，内存占有大约在2.5G，且保持硬盘读取。

（已经fork了，不知道啥时候有时间仔细研究一下😂）

**Comment by lqzhgood** [comment]
从现象看好像 `-Xmx` 并没有被传递给 `Java`， 你设置一个系统级的全局变量看看可以不？ 我也不知道 `exe4j` 是如何封装的

- 运行  `sysdm.cpl`
- 高级 - 环境变量
- 系统变量 - 新建 
- 名 JAVA_OPTS 值 `-server -Xms4096m -Xmx4096m -Xss512k`
- 重新打开一个 cmd，执行 `echo %JAVA_OPTS%` 有以上值的输出
- 执行 `npm run build`

#################

如果以上不行，你直接从 `java` 源码执行试试，可以修改这一行 
https://github.com/lqzhgood/Shmily-Get-Wechat/blob/0bfbe1d36ce1bde3f74ec71f5e935b4c94ff69af/export/db-android/2%20dbToJson/lib/decodeMessageTable/test/src/sqlite/test/ReadTxt.java#L29

```
 String sql = "select * from message where talker='FILTER_USER'"; 
```
这样只会处理指定用户的数据，而不是处理全部数据库

**Comment by Coooolfan** [comment]
感谢您的解答，我参照您提供的方法直接修改java源码的命令，通过指定wxid成功导出了数据。

可惜wxid对用户不可见，数据库中存储的是用户的原始wxid而不是可以的id。
1. 在Windows下可以使用DBeaver软件可视化数据库，打开被解密的数据库。
2. 在表中找到表格`message`，双击后选择右侧的`数据`按钮，右键表头`talker`，选择`过滤器-按数值过滤`，可以看到以数量排序后的结果。

**Comment by lqzhgood** [comment]
你是说 `talker` 不等于 `微信号` 吗？
![image](https://github.com/lqzhgood/Shmily-Get-Wechat/assets/9134671/f50fa412-e2e9-4b69-8e54-7aba6951cf47)

**Comment by lqzhgood** [comment]
另外https://github.com/lqzhgood/Shmily-Get-Wechat/issues/2#issuecomment-1574554341 提到的 `[全局变量]` 方式可行吗？
如果可行我写到文档里面去，毕竟不是每个人都能改 `源码`

**Comment by lqzhgood** [comment]
你现在的数据应该是从自己的设备导出的吧，所以 `config.js` 的 `isFromOtherAccount` 默认值应该是 `false`，不知道你修改了没

https://github.com/lqzhgood/Shmily-Get-Wechat/blob/efc2793fe03ea9978c5be81cd58da85b75caa6ab/ToMsg/config.js#LL10C4-L10C4

**Comment by ppBruce** [comment]
> 

我这边本机测试全局变量的方法不可行。

**Comment by lqzhgood** [comment]
重新编译了一下，添加了 `-Xmx16384m` / 最大使用内存 16G 的参数

`2dbToJson` 为主目录
- 把 `decodeMessageTable.exe` 替换 `/lib/decodeMessageTable/Releases/decodeMessageTable.exe`
- `decodeMessageTable.exe` 放到 `input` 下 


重新执行 `npm run build` 试试~

你试试这个~ 如果可以反馈一下


[decodeMessageTable.zip](https://github.com/lqzhgood/Shmily-Get-Wechat/files/11673839/decodeMessageTable.zip)

**Comment by ppBruce** [comment]
> 重新编译了一下，添加了 `-Xmx16384m` / 最大使用内存 16G 的参数
> 
> `2dbToJson` 为主目录
> 
> * 把 `decodeMessageTable.exe` 替换 `/lib/decodeMessageTable/Releases/decodeMessageTable.exe`
> * `decodeMessageTable.exe` 放到 `input` 下
> 
> 重新执行 `npm run build` 并关注一下 `内存使用峰值` 试试~
> 
> @ppBruce 你试试这个~ 如果可以反馈一下
> 
> [decodeMessageTable.zip](https://github.com/lqzhgood/Shmily-Get-Wechat/files/11673839/decodeMessageTable.zip)

谢谢！
没再报内存溢出了。
我decrypted_database.db 1.17GB，运行欧中最高内存到了15.6G（可用总共15.8）。最终还是失败了，报了另一个错：
正在解密 Message
FILTER_USER [ 'wxid_gbxxxxxx1' ]
node:buffer:652
    slice: (buf, start, end) => buf.utf8Slice(start, end),
                                    ^

Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (node:buffer:652:37)
    at Buffer.toString (node:buffer:871:14)
    at Object.readFileSync (node:fs:513:41)
    at Module._extensions..json (node:internal/modules/cjs/loader:1314:22)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\wechat\tools\Shmily-Get-Wechat-main\export\db-android\2 dbToJson\index.js:23:13)
    at Module._compile (node:internal/modules/cjs/loader:1254:14) {
  code: 'ERR_STRING_TOO_LONG'
}

Node.js v18.16.0

**Comment by ppBruce** [comment]
> 从现象看好像 `-Xmx` 并没有被传递给 `Java`， 你设置一个系统级的全局变量看看可以不？ 我也不知道 `exe4j` 是如何封装的
> 
> * 运行  `sysdm.cpl`
> * 高级 - 环境变量
> * 系统变量 - 新建
> * 名 `JAVA_OPTS` 值 `-server -Xmx4096m`
> * 重新打开一个 cmd，执行 `echo %JAVA_OPTS%` 有以上值的输出
> * 执行 `npm run build`
> 
> #################
> 
> 如果以上不行，你直接从 `java` 源码执行试试，可以修改这一行
> 
> https://github.com/lqzhgood/Shmily-Get-Wechat/blob/0bfbe1d36ce1bde3f74ec71f5e935b4c94ff69af/export/db-android/2%20dbToJson/lib/decodeMessageTable/test/src/sqlite/test/ReadTxt.java#L29
> 
> ```
>  String sql = "select * from message where talker='FILTER_USER'"; 
> ```
> 
> 这样只会处理指定用户的数据，而不是处理全部数据库

感觉这个方法可能适合我一点，我没太有编程基础，只能边百度边做。
修改代码后如何重新生成exe有没有简单指引？eclipse + exe4j? 谢谢！

**Comment by lqzhgood** [comment]
那就是使用内存爆了，除了加内存就没办法了。

如果从源码跑，就不用生成 exe 了，安装完 java 环境，
`IDE` 进入 decodeMessageTable 目录， 数据库也放到这个目录
在  `test/src/sqlite/test/ReadTxt.java` 的入口 `main` 上执行就行了
