### ISSUE TITLE
[Bug]"emojiByWx"和"xml2json"报错

### ISSUE THREAD

**Issue by hitech-h** [lqzhgood/Shmily-Get-Wechat#5]
关键信息
"emojiByWx"

```
npm run emojiByBase
> export@1.0.0 emojiByBase
> node ./lib/emojiByBase/index.js

未处理 Emoji 数量 140 140

D:\Shmily\ToMsg\lib\emojiByWx\index.js:31
        v.packName = v.packName.replaceAll("\b", "").trim();
                                ^

TypeError: Cannot read properties of null (reading 'replaceAll')
    at D:\Shmily\ToMsg\lib\emojiByWx\index.js:31:33
    at Array.map (<anonymous>)
    at Object.<anonymous> (D:\Shmily\ToMsg\lib\emojiByWx\index.js:30:6)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.16.1
```
"xml2json"

```
处理的消息长度 126243
D:\Shmily\ToMsg\node_modules\xml2json\lib\xml2json.js:173
        throw new Error('There are errors in your xml file: ' + parser.getError());
              ^

Error: There are errors in your xml file: syntax error
    at module.exports [as toJson] (D:\Shmily\ToMsg\node_modules\xml2json\lib\xml2json.js:173:15)
    at xmlToJSON (D:\Shmily\ToMsg\convert\utils\index.js:14:27)
    at typeMap (D:\Shmily\ToMsg\convert\android\typeMap.js:51:25)
    at androidToMsg (D:\Shmily\ToMsg\convert\android\index.js:36:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ToMsg (D:\Shmily\ToMsg\convert\index.js:10:19)
    at async D:\Shmily\ToMsg\index.js:65:20

Node.js v18.16.1
```

<details>
<summary>过程</summary>

执行'npm run andriod‘时，发现'emojiByWx'报错。查阅资料，更改'ToMsg\lib\emojiByWx\index.js’第31行为

```
       v.packName = v.packName?.replaceAll("\b", "").trim();
```
跳过了该报错（应该？），后续就是'xml2json'报错
</details>

<details>
<summary>input文件夹详情</summary>

```
-input
    -assets
        -image
        -image2
        -voice2
        -……
    -copyToData
        -[空]
    -JSON
        -android
            -BLOB
            -EmotionDetailInfo
            -……
            -db-android_msg_res.json
            -……
            -voiceinfo.json
    -localFiles
        -xxx.xxx
        -……
```
</details>
大佬有空可以看看，感谢

**Comment by lqzhgood** [comment]
> input/JSON/android/EmojiGroupInfo.json
> input/JSON/android/EmotionDetailInfo.json

// 我看到你发的 input 文件夹详情中有一个 EmotionDetailInfo，但是没有 .json 的后缀，这个是你漏写了还是文件本身没 .json 后缀？

这两个文件有么？ 应该是在 `dbToJson` 这个环节生成的。

如果有的话发过来看看~

**Comment by hitech-h** [comment]
应该是有这两个文件的
不过目前文件暂不在身边，周末再发吧

**Comment by hitech-h** [comment]
>input/JSON/android/EmojiGroupInfo.json
input/JSON/android/EmotionDetailInfo.json

两个文件均存在

在`input/JSON/android/EmojiGroupInfo.json`发现
```
……
        "packName": null,
……
```
不知道是不是因为这个原因
文件已发送至您邮箱了

**Comment by lqzhgood** [comment]
```
 "productID": "com.tencent.xin.emoticon.ali2g",          //表情ID：  腾讯官方.微信.表情.ali2g
 "packName": null, // 表情包名字
 “lastUseTime” : 1693574381403// 最后更新时间    new Date(1693574381403).toLocaleString() -> 转为人类可读
```
的这些表情包是不是都失效 / 下架 了？
你随便抽几个, 比如  1693574381403 这个

**Comment by lqzhgood** [comment]
更新一下 `ToMsg/lib/emojiByWx/index.js` 就可以了。

**Comment by hitech-h** [comment]
`emojiByWx`的报错已解决

> 这些表情包是不是都失效 / 下架 了？
你随便抽几个, 比如 1693574381403 这个

这不太清楚怎么验证是否失效哦（但大概率是）

另，`xml2json`的报错仍存在，且和上面一样
排查了许久也不清楚是什么原因，抛出错误的是哪个`.xml`文件
有空可否告知一下？

**Comment by lqzhgood** [comment]
是在 `D:\Shmily\ToMsg\convert\utils\index.js:14` 14行抛出的错误
```
function xmlToJSON(source, _xml = '') {
    if (_.isPlainObject(_xml)) return _xml;
    let xml;
    if (!xml) xml = _xml;
    console.log('error xml:', _xml);  // <--- 增加这一行会打印出数据， 报错前的这个发出看看
    const json = xml2json.toJson(xml, {
        object: true,
        trim: false,
    });
    return emptyObjectToString(json);
}
```

**Comment by hitech-h** [comment]
加入`console.log('error xml  --->|', _xml,'|<-----');`后报错的结果如下：

```
#隐私信息通过***隐藏
#部分信息通过……省略
处理的消息长度 126243
VM533 index.js:14 error xml  --->| <msg username="***" nickname="***" alias="***" fullpy="***" shortpy="***" imagestatus="3" scene="17" province="***" city="***" sign="***" percard="0" sex="0" certflag="24" certinfo="***" certinfoext="" brandIconUrl="http://***" brandHomeUrl="" brandSubscriptConfigUrl="" brandFlags="" regionCode="***"/> |<-----
VM533 index.js:14 error xml  --->| wxid_***:
<?xml version="1.0"?>
<msg>
	<appmsg appid="" sdkver="0">
		<title>考͏验友谊的时候到了！请帮点一下↓↓</title>
		<des>我在免费领【迷你电风扇】，你不来领一件吗？</des>
		<username />
		<action>view</action>
		<type>5</type>
		<showtype>0</showtype>
		<content />
		<url>https://***</url>
		<lowurl />
		<dataurl />
		<lowdataurl />
		<contentattr>0</contentattr>
……
	</appinfo>
	<commenturl></commenturl>
</msg>
 |<-----
VM537 xml2json.js:173 Uncaught Error: There are errors in your xml file: syntax error
    at module.exports [as toJson] (D:\Shmily\ToMsg\node_modules\xml2json\lib\xml2json.js:173:15)
    at xmlToJSON (D:\Shmily\ToMsg\convert\utils\index.js:15:27)
    at typeMap (D:\Shmily\ToMsg\convert\android\typeMap.js:51:25)
    at androidToMsg (D:\Shmily\ToMsg\convert\android\index.js:36:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ToMsg (D:\Shmily\ToMsg\convert\index.js:10:19)
    at async D:\Shmily\ToMsg\index.js:65:20
```

推测为

```
VM533 index.js:14 error xml  --->| wxid_***:
<?xml version="1.0"?>
……
```

```
"content": "wxid_***:\n<?xml version=\"1.0\"?>\n<msg>\n\t<appmsg appid=\"\" sdkver=\"0\">\n…… #此为在json文本中的值
```

中`wxid_***:\n`存在导致xml格式不规范。删去`wxid_***:\n`后可继续正常运行，看了一下发现几乎所有的`xml`格式的文本都有这样的问题。

**Comment by lqzhgood** [comment]
那就是微信结构改了~
 
[ToMsg.zip](https://github.com/lqzhgood/Shmily-Get-Wechat/files/13063005/ToMsg.zip)

你用这个替换后在执行
- 会把有问题的 xml type 写到 `wxid_xml.json`，然后把这个发出来
- 然后会打印每条消息的详情，你看看 `wxid_***` 这个 `***` 和 `v` 的哪个字段一样，方便对 xml 进行处理

**Comment by hitech-h** [comment]
好

由于一些原因我需要重新配置`nodejs`环境，可能要一定时间，我尽量在明晚之前发出

**Comment by hitech-h** [comment]
抱歉，由于一些原因，还未能配置完成，可能还需要几天时间。请见谅

**Comment by lqzhgood** [comment]
没那么急~  take it easy

**Comment by hitech-h** [comment]
还是等到了周末

`wxid_xml.json`中内容如下

```
[
    "49"
]
```

所打印的字段`v`中（`wxid`用`wxid_1234567890`代替，感觉这样更直观点）
```
v {
  bizChatId: '-1',
  bizChatUserId: null,
  bizClientMsgId: null,
  content: 'wxid_1234567890:\n' +
    '<?xml version="1.0"?>\n' +
    '<msg>\n' +
    '\t<appmsg appid="" sdkver="0">\n' +
    '\t\t<title>考͏验友谊的时候到了！请帮点一下↓↓</title>\n' +
    '\t\t<des>我在免费领【迷你电风扇】，你不来领一件吗？</des>\n' +
……
    '\t</appmsg>\n' +
    '\t<fromusername>wxid_1234567890</fromusername>\n' +
    '\t<scene>0</scene>\n' +
……
    '\t</appinfo>\n' +
    '\t<commenturl></commenturl>\n' +
    '</msg>\n',
  createTime: '1532257922000',
……
  reserved: {
    msg: {
      appmsg: [Object],
      commenturl: '',
      appinfo: [Object],
      fromusername: 'wxid_1234567890',
      scene: '0'
    }
},
  status: '4',
……
  type: '49'
}
```
以上就是所有包含`wxid_1234567890`的文本

**Comment by lqzhgood** [comment]
更新一下 `ToMsg\convert\utils\index.js` 这个文件再试试

**Comment by hitech-h** [comment]
仍报错
```
处理的消息长度 126243
D:\Shmily\ToMsg\node_modules\xml2json\lib\xml2json.js:173
        throw new Error('There are errors in your xml file: ' + parser.getError());
              ^

Error: There are errors in your xml file: XML or text declaration not at start of entity
    at module.exports [as toJson] (D:\Shmily\ToMsg\node_modules\xml2json\lib\xml2json.js:173:15)
    at xmlToJSON (D:\Shmily\ToMsg\convert\utils\index.js:20:27)
    at typeMap (D:\Shmily\ToMsg\convert\android\typeMap.js:51:25)
    at androidToMsg (D:\Shmily\ToMsg\convert\android\index.js:36:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ToMsg (D:\Shmily\ToMsg\convert\index.js:10:19)
    at async D:\Shmily\ToMsg\index.js:65:20

Node.js v18.16.1
```
搜索`XML or text declaration not at start of entity`推测其原因为**第一行有空格或者回车等的符号**[[csdn原帖](https://blog.csdn.net/Alan_java88/article/details/54891331)]

**Comment by lqzhgood** [comment]
更新一下 ToMsg\convert\utils\index.js 这个文件再试试

如果还报错，麻烦修改 `ToMsg\convert\utils\index.js`  15 -18 行
 
``` js
if (xml.startsWith('wxid_')) {
     fs.writefilesync(`./${Date.now()}.xml`,  xml); // 新增这一行
     xml = xml.split(':')[1].trim();
}
```
然后在执行目录下会生成一个名字类似于 `16990616******.xml` 的文件，把这个发给我

**Comment by hitech-h** [comment]
仍报错
已发至邮箱

**Comment by lqzhgood** [comment]
可以了，更新一下 ToMsg\convert\utils\index.js

`xml = xml.split(':')[1].trim();`   ->  `xml = xml.replace(/^wxid_.+\n/, '');`

**Comment by hitech-h** [comment]
仍有报错`There are errors in your xml file: syntax error`

> console.log('error xml  --->|', _xml,'|<-----');  // <--- 增加这一行会打印出数据， 报错前的这个发出看看

添加了这行代码查看报错的`xml`
发现是因为，不仅可能**会有  wxid_1234567890:\n<?xml version="1.0"?> 开头的情况**，还有可能有如下情况

```
error xml  --->| shouji41726381:
<msg><appmsg appid="" sdkver="0"><title>title</title>……
```

```
723817192731@openim:\n<msg>\n  <appmsg appid=\"\" sdkver=\"0\">\n    <title>……
```

即`xml`之前有一段字符串的情况
还有更多，就不一一列举了
但它们都是在**群聊**聊天记录出现的

感觉是因为，我在`dbToJson`导出了所有聊天记录，导致`db-android_msg_res.json`中存在群聊聊天记录。我定位个人与个人的聊天，就没有发现这种现象，`xml`格式都是正常且完整的。

个人感觉此类问题不需要解决了。接下来我会试试在`dbToJson`用wxid导出
给大佬添麻烦了。问题算是完成了吧

**Comment by lqzhgood** [comment]
如果群聊的消息格式都是 
```
xxxxx:\n <msg><appmsg appid....          // \n 是换行的意思
```
那么也好处理, 只需要把第一行去掉就行了.

问题在于 `群聊` 和 `个人` 是否有明显的标识符用于区别
可以把这一行的 `//` 去掉, 就会在处理前打印本条消息
https://github.com/lqzhgood/Shmily-Get-Wechat/blob/3fa95ba6382c7f4a8c1890b0a77e18e27ab5cce6/ToMsg/convert/android/index.js#L29


然后对比  `群聊` 和 `个人` 是否有属性值用于区别

**Comment by hitech-h** [comment]
简单观察对比一下，`db-android_msg_res.json`的`JSON`都有一个`talker`
如果是个人，一般为
`"talker": "wxid_abcd123456efgh"`
如果是群聊，一般为
`"talker": "1234567890@chatroom",`
此外，群聊的`content`也有些特殊，一般为
`"content": "wxid_abcd123456efgh:\n说的话"`
个人的则不会有`wxid_abcd123456efgh:\n`这个前缀
估计`xml2json`的报错也出自于此

**Comment by lqzhgood** [comment]
我不太明白你说的这个 "群聊" 的定义,
例如有个 talker 的值是  xxx@chatroom , content 是 abcded

那么这条消息 abcded 是在某个群聊里面吗?
还是说这个人是从群聊中添加的,  abcded 是你和这个人的单独聊天的对话?

**Comment by hitech-h** [comment]
在`dbToJson`，若导出所有数据库，那么在`/dist/db-android_msg_res.json`中，就会存在个人、群聊（可能公众号也有）等的聊天数据

以下一些涉及个人隐私的信息会打乱字符
个人的JSON值如下：
```
    {
        "bizChatId": "-1",
        "bizChatUserId": null,
        "bizClientMsgId": "",
        "content": "学一学",
        "createTime": "1826481626182",
        "flag": "0",
        "hasXml": [],
        "imgPath": null,
        "isSend": "0",
        "isShowTimer": null,
        "lvbuffer": "$~BLOB~lvbuffer$",
        "msgId": "106491",
        "msgSeq": "762846182",
        "msgSvrId": "9274916295492730294",
        "reserved": null,
        "status": "3",
        "talker": "wxid_82d27g291sd9so",
        "talkerId": "2008",
        "transBrandWording": null,
        "transContent": null,
        "type": "1"
    }
```

群聊的JSON值如下：
```
    {
        "bizChatId": "-1",
        "bizChatUserId": null,
        "bizClientMsgId": null,
        "content": "wxid_jsa8wjsbd81hd4:\n问题不大",
        "createTime": "1183621468213",
        "flag": "0",
        "hasXml": [],
        "imgPath": null,
        "isSend": "0",
        "isShowTimer": null,
        "lvbuffer": "$~BLOB~lvbuffer$",
        "msgId": "2360",
        "msgSeq": "699999203",
        "msgSvrId": "9128648172831235131",
        "reserved": null,
        "status": "4",
        "talker": "94721746124@chatroom",
        "talkerId": "110",
        "transBrandWording": null,
        "transContent": null,
        "type": "1"
    }
```
其中`content`的`wxid_jsa8wjsbd81hd`为发言者，`问题不大`是发言内容。群聊中的`talker`由一串数字加`@chatroom`组成，那一串数字算是和群号差不多的东西？

故群聊的`xml`也会以`wxid_jsa8wjsbd81hd4:\n`为头

**Comment by lqzhgood** [comment]
还是更新一下 ` ToMsg\convert\utils\index.js` 看是否还报错
我把第一行直接去掉了.

**Comment by hitech-h** [comment]
已解决

**Comment by lqzhgood** [comment]
> 已解决

好的, 我下周会再更一版, 把第一行的 wxId 换成对应 昵称
